Add device id and some user properties
DenisNP/Amplitude pull request #1
Opened 2021-02-09 02:54 UTC by nathankim0

2021-02-10 15:06 UTC, DenisNP requested changes
First of all, thank you for the PR!

I've added some comments, please, take a look

2021-02-10 15:06 UTC, DenisNP commented on Amplitude/Amplitude.cs
> +using Xamarin.Essentials;
This is universal library for any runtime. Please, do not use Xamarin or other platform-dependent namespaces.

2021-02-10 15:06 UTC, DenisNP commented on Amplitude/Amplitude.cs
> +        //private Amplitude(string deviceId, Dictionary<string, object> userProperties = null)
Commented code can be removed, I suppose.

2021-02-10 15:06 UTC, DenisNP commented on Amplitude/Amplitude.cs
> +        public static Amplitude InstanceFor(string userId, string deviceId, bool storeInstance = false, Dictionary<string, object> userProperties = null)
I don't think that DeviceId is required property for all cases. E.g.: chat-bot, web application can not know about user device. So, at least this constructor should be in additional to the minimal one, without DeviceId.

2021-02-13 01:29 UTC, nathankim0 commented
Thanks for the comment. As a junior developer, it has helped me a lot. I will close the pull request.

2021-02-13 01:29 UTC, closed without merging